export const PATH = {
  dashboard: "/",
  login: "/login",
  signUp: "/signup",
  forgotPassowrd: "/forgot-password",
  analytics: "/analytics",
  admin: "/admin",
  package: "/package",
  addPackage: "/package/addPackage",
  location: "/location",
  continent: "/continent",
  country: "/country",
  tourType: "/tour_type",
  accommodations: "/accommodations",
  activities: "/activities",
  ageRange: "/age_range",
  transport: "/transport",
  booking: "/booking",
  settings: "/settings",
  enquiry: "/enquiry",
  meals: "/meals",
  updatePackage: "/update-package",
  "message": "/message"
};
